---
title: "sript_beta_diversity_functions"
output: html_document
date: "2025-04-03"
---
```{r}
library(vegan)
library(glue)
library(cowplot)

````







```{r}
#load the meta data

ko_meta <- read_excel("meta_KO.xlsx")

ko_meta <- column_to_rownames(ko_meta, var = names(ko_meta) [1])

rownames(ko_meta) <- gsub("-", "_", rownames(ko_meta))

ko_meta <- ko_meta[rownames(ko_meta) != "t3_rocks_summer", ]


write.csv(ko_meta, "ko_meta.xlsx", row.names = TRUE)

rownames(ko_meta)

#we have to transpose the counts matrix
counts <- read_excel("all13 no normalized NO transposed.xlsx")

counts_t <- t(counts)

str(counts_t)

counts_df <- as.data.frame(counts, stringsAsFactors = FALSE)

rownames(counts_df) <- counts_df[, 1]
counts_df <- counts_df[, -1]  # Remove the KO column now in rownames

counts_df[] <- lapply(counts_df, as.numeric)

counts_t <- as.data.frame(t(counts_df))

#then we normalize the data using the total number of reads after the assembly

total_reads <- c(
  "t0_water_winter" = 91080040,
  "t1_water_winter" = 105155034,
  "t2_water_winter" = 126922246,
  "t3_water_winter" = 118719880,
  "t0_water_summer" = 101551626,
  "t1_water_summer" = 118387904,
  "t2_water_summer" = 124541282,
  "t3_water_summer" = 96596350,
  "t1_rocks_winter" = 4360034,
  "t2_rocks_winter" = 106865534,
  "t3_rocks_winter" = 102643344,
  "t1_rocks_summer" = 729672,
  "t2_rocks_summer" = 13529884
)

str(counts)

str(total_reads)

dim(dist_functions)
attr(dist_functions, "Size")

normalized_counts <- sweep(counts_df, 2, colSums(counts_df), FUN = "/")

normalized_counts_t <- sweep(counts_df, 2, total_reads[colnames(counts_df)], FUN = "/")

#we calculate the hellinger and bray curtis

functions_hellinger = decostand(normalized_counts_t, method = "hellinger")

dist_functions = vegdist(t(functions_hellinger), method = "bray")


PCOA.hellinger = cmdscale(dist_functions, eig = TRUE, add = TRUE)

position.nn = PCOA.hellinger$points

colnames(position.nn) = c("Axis.1", "Axis.2")

percent_explained.nn = 100*PCOA.hellinger$eig/sum(PCOA.hellinger$eig) 

reduced_percent.nn = format(round(percent_explained.nn[1:2], digits = 2), nsmall = 1, trim = TRUE)


pretty_labs.nn = c(glue("Axis 1 ({reduced_percent.nn[1]}%)"), glue("Axis 2 ({reduced_percent.nn[2]}%)")) 

df.nn = merge(position.nn, ko_meta, by = "row.names") 
rownames(df.nn) <- df.nn$Row.names
df.nn = df.nn[-1]

df.nn$lifestyle <- str_to_title(df.nn$lifestyle)



b.lifestyle <- ggplot(df.nn, aes(x = Axis.1, y = Axis.2, color = lifestyle)) + 
  custom_theme() + 
  geom_point(size = 3.5, position = position_jitter(width = 0.02, height = 0.02)) + 
  labs(
    x = pretty_labs.nn[1], 
    y = pretty_labs.nn[2], 
    color = "Lifestyle", 
    shape = "Season"
  ) + 
  scale_y_continuous(limits = c(-1.2, 1.2), expand = c(0, 0)) + 
  scale_x_continuous(limits = c(-1.2, 1.2), expand = c(0, 0)) + 
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.2) + 
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.2) + 
  scale_color_manual(values = c("darkblue", "darkgreen")) +
  stat_ellipse(aes(group = lifestyle), level = 0.95) +
  guides(
    color = guide_legend(
      byrow = TRUE,
      label.theme = element_text(size = 17, margin = margin(b = 8))
    )
  ) +
  theme(
    legend.title = element_text(size = 20),
    legend.box = "vertical",
    axis.title = element_text(size = 17),
    axis.text = element_text(size = 17),
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA)
  )

# Save as SVG with transparency
ggsave(
  filename = "beta.l.svg",
  plot = b.lifestyle,
  device = "svg",
  width = 10,
  height = 6,
  units = "in",
  dpi = 300
)


````

````{r}

df.nn$season <- str_to_title(df.nn$season)

B.season <- ggplot(df.nn, aes(x = Axis.1, y = Axis.2, color = season)) + 
  custom_theme() + 
  geom_point(size = 3.5, position = position_jitter(width = 0.02, height = 0.02)) + 
  labs(
    x = pretty_labs.nn[1], 
    y = pretty_labs.nn[2], 
    color = "Season"
  ) + 
  scale_y_continuous(limits = c(-1.2, 1.2), expand = c(0, 0)) + 
  scale_x_continuous(limits = c(-1.2, 1.2), expand = c(0, 0)) + 
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.2) + 
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.2) + 
  scale_color_manual(values = c("darkred", "darkblue")) +
  stat_ellipse(aes(group = season), level = 0.95) +
  guides(
    color = guide_legend(
      byrow = TRUE,
      label.theme = element_text(size = 17, margin = margin(b = 8))
    )
  ) +
  theme(
    legend.title = element_text(size = 20),
    legend.box = "vertical",
    axis.title = element_text(size = 17),
    axis.text = element_text(size = 17),
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA)
  )

# Save as SVG with transparent background
ggsave(
  filename = "beta_season.svg",
  plot = B.season,
  device = "svg",
  width = 10,
  height = 6,
  units = "in",
  dpi = 300
)

beta_s <- ggdraw(beta_s) +
  draw_plot_label(label = "B)", x = 0.001, y = 1.01, size = 18, fontface = "bold")

print(beta_s)



ggsave(filename = "beta_season.svg", plot = B.season, device= "svg", width = 10, height = 6, units = "in", dpi = 300)


````




````{r}

all(rownames(ko_meta) == labels(dist_functions))

ko_meta <- ko_meta[labels(dist_functions), ]

stopifnot(all(rownames(ko_meta) == labels(dist_functions)))
#testing permanova



adonis2(dist_functions ~ lifestyle, data = ko_meta, permutations = 9999)



adonis2(dist_functions ~ season, data = ko_meta, permutations = 9999)






````








